# Generated by Django 4.2.4 on 2023-09-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_consert_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_booking_history',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ticket_booking_history',
            name='user_name',
        ),
    ]
