# Generated by Django 4.2.4 on 2023-09-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_consert_app', '0002_remove_ticket_booking_history_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_booking',
            old_name='ticket',
            new_name='ticket_count',
        ),
        migrations.RemoveField(
            model_name='ticket_booking',
            name='consert_id',
        ),
    ]
