# Generated by Django 4.2.4 on 2023-09-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_consert_app', '0003_rename_ticket_ticket_booking_ticket_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('ticket_count', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ticket_count', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket_booking_history',
            name='consert_id',
        ),
        migrations.RemoveField(
            model_name='ticket_booking_history',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Ticket_Booking',
        ),
        migrations.DeleteModel(
            name='Ticket_Booking_History',
        ),
    ]
